Fix missing include of iostream
As without it the test just happily fails to compile due to this:

tests/zypp/Flags_test.cc:9:12: error: ‘std::cout’ has not been declared